version: "3.8"

services:
  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server/node:/app/node
    ports:
      - "8000:8000"
    restart: always

  vitejs_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    restart: always